name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '**'

  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**'

jobs:
  test:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          python-version: ${{ matrix.python-version }}
          cache-suffix:  ${{ matrix.python-version }}

      - name: Setup Test Results
        run: |
          mkdir -p ${{ github.workspace }}/build/coverage
          mkdir -p ${{ github.workspace }}/build/test-results

      - name: Run tests and collect coverage
        run: |
          set -euox pipefail
          PACKAGE=$(echo "$(basename $PWD)" | tr "-" "_")
          [ -d "${PACKAGE}" ] || PACKAGE="."
          uv run --frozen pytest --cov-report=xml:${{ github.workspace }}/build/coverage/coverage.xml --cov="${PACKAGE}" --junitxml=${{ github.workspace }}/build/test-results/tests.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/*.xml'

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
